language: node_js
cache: bundler
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js: stable
before_script:
  - npm install -g npm@4
  - npm install -g bower 
  - npm install -g polymer-cli
  - bower install
cache: yarn
script:
  - cd /home/travis/build/jukbot/smart-industry
  - polymer build
  - xvfb-run npm test
notifications:
  email: false
