language: node_js
cache: bundler
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js: stable
before_script:
  - npm install -g npm@4
  - npm install -g bower 
  - npm install -g polymer-cli
  - node -v
  - npm -v
  - polymer --version
  - bower install
cache: yarn
script:
  - ls
  - mkdir build/default
  - polymer build
notifications:
  email: false
