language: node_js
node_js: 
  - "6"
cache: bundler
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js: stable
before_install:
  - npm install -g npm@4
install:
  - npm install -g yarn
  - npm install -g bower 
  - npm install -g polymer-cli
  - node -v
  - npm -v
  - polymer --version
  - npm install
  - bower install
before_script:
  - mkdir -p build/default
  - ls
script:
  - polymer build
  - polymer serve
notifications:
  email: false
