language: node_js
node_js: 
  - "6"
cache: bundler
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js: stable
before_script:
  - npm install -g yarn
  - npm install -g bower 
  - npm install -g polymer-cli
  - node -v
  - npm -v
  - polymer --version
  - npm install
  - bower install
cache: yarn
script:
  - ls
  - mkdir -p build/default
  - polymer build
notifications:
  email: false
